name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chess_app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install
        cd client && npm install

    - name: Run tests
      run: |
        npm test
        cd client && npm test
      env:
        CI: true
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: chess_app_test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/chess_app_test

    - name: Build
      run: |
        cd client && npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: cs144-25s-srinathsai22-459406
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to VM
      run: |
        echo "Starting VM if stopped..."
        gcloud compute instances start cs144-25s-srinathsai22 --zone=us-west1-a
        
        echo "Waiting for VM to be ready..."
        sleep 30
        
        echo "Copying files to VM..."
        gcloud compute scp --recurse ./client/dist/* cs144-25s-srinathsai22:~/chess-app/client/dist --zone=us-west1-a
        gcloud compute scp --recurse ./server/* cs144-25s-srinathsai22:~/chess-app/server --zone=us-west1-a
        gcloud compute scp package.json package-lock.json cs144-25s-srinathsai22:~/chess-app --zone=us-west1-a
        
        echo "Setting up environment and restarting service..."
        gcloud compute ssh cs144-25s-srinathsai22 --zone=us-west1-a --command="
          cd ~/chess-app && \
          npm install && \
          pm2 restart all || pm2 start npm --name 'chess-app' -- start
        "
        
        echo "Deployment completed!" 